import { createContext, useContext, useEffect, useMemo, useState } from 'react'

export const languages = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'bho', name: 'Bhojpuri', native: 'भोजपुरी' },
]

const messages = {
  en: {
    flights: 'Flights', insights: 'Route insights', trends: 'Fare trends', help: 'Help', signIn: 'Sign in', dashboard: 'Account', language: 'Language',
    kicker: 'A SMARTER WAY TO FLY ACROSS INDIA', headline1: 'Go where you want.', headline2: 'Know what to pay.', heroText: 'Is that fare actually good? Compare it with similar trips, find a better travel date, and keep the routes you care about close.', explore: 'Explore a route', how: 'See how it works', start: 'START HERE', where: 'Where are you flying?', choose: 'Choose a covered route. The map updates with your trip.', from: 'FROM', to: 'TO', check: 'Check this route', quick: 'QUICK PICKS', simulated: 'Fare analysis uses simulated observations.',
    way: 'THE SKYMETRICS WAY', story1: 'The fare is a number.', story2: 'The decision has a story.', storyText: 'Look beyond the price tag. SkyMetrics turns fare patterns into a clearer next step for your trip.', context: 'PRICE CONTEXT', contextTitle: 'Is it a good fare for this trip?', contextText: 'See how the fare compares with trips on the same route and at a similar booking time.', contextAction: 'Check a fare', dates: 'DATE FLEXIBILITY', datesTitle: 'One day can change the price.', datesText: 'Compare nearby departure dates before you settle on one.', datesAction: 'Explore dates', trips: 'YOUR TRIPS', tripsTitle: 'Keep an eye on what matters.', tripsText: 'Save trips, watch routes and set a target price in your account.', tripsAction: 'Open your dashboard', closingLabel: 'YOUR NEXT TRIP STARTS WITH A BETTER QUESTION', closing: 'Ready to look beyond the price?', getStarted: 'Get started', dataNote: 'SkyMetrics is a research prototype using simulated Indian domestic fares. It does not show live ticket prices or official government CPI.',
  },
  hi: {
    flights: 'उड़ानें', insights: 'रूट की जानकारी', trends: 'किराए का रुझान', help: 'मदद', signIn: 'साइन इन', dashboard: 'खाता', language: 'भाषा',
    kicker: 'भारत में उड़ान का बेहतर तरीका', headline1: 'जहाँ चाहें जाएँ।', headline2: 'सही किराया समझें।', heroText: 'क्या यह किराया सच में अच्छा है? समान यात्राओं से तुलना करें, सस्ती तारीख खोजें और अपने पसंदीदा रूट पर नज़र रखें।', explore: 'रूट देखें', how: 'यह कैसे काम करता है', start: 'यहाँ से शुरू करें', where: 'आप कहाँ उड़ रहे हैं?', choose: 'उपलब्ध रूट चुनें। नक्शा आपकी यात्रा के साथ बदल जाएगा।', from: 'कहाँ से', to: 'कहाँ तक', check: 'रूट जाँचें', quick: 'लोकप्रिय रूट', simulated: 'किराए का विश्लेषण सिम्युलेटेड डेटा पर आधारित है।',
    way: 'SKYMETRICS कैसे मदद करता है', story1: 'किराया सिर्फ एक संख्या है।', story2: 'फ़ैसले के पीछे एक कहानी है।', storyText: 'सिर्फ कीमत नहीं, उसके पीछे का रुझान भी देखें। SkyMetrics आपकी यात्रा के लिए अगला कदम समझने में मदद करता है।', context: 'किराए की तुलना', contextTitle: 'क्या इस यात्रा के लिए यह किराया अच्छा है?', contextText: 'एक ही रूट और समान बुकिंग समय वाली यात्राओं से किराए की तुलना करें।', contextAction: 'किराया जाँचें', dates: 'तारीख चुनें', datesTitle: 'एक दिन से कीमत बदल सकती है।', datesText: 'यात्रा की तारीख तय करने से पहले आसपास की तारीखें देखें।', datesAction: 'तारीखें देखें', trips: 'आपकी यात्राएँ', tripsTitle: 'ज़रूरी रूट पर नज़र रखें।', tripsText: 'अपने खाते में यात्रा सेव करें, रूट देखें और लक्ष्य किराया तय करें।', tripsAction: 'डैशबोर्ड खोलें', closingLabel: 'अगली यात्रा की शुरुआत बेहतर सवाल से', closing: 'क्या आप कीमत को बेहतर समझना चाहेंगे?', getStarted: 'शुरू करें', dataNote: 'SkyMetrics सिम्युलेटेड भारतीय घरेलू किरायों पर आधारित शोध प्रोटोटाइप है। यहाँ लाइव टिकट कीमतें या आधिकारिक सरकारी CPI नहीं हैं।',
  },
  bn: {
    flights: 'ফ্লাইট', insights: 'রুটের তথ্য', trends: 'ভাড়ার প্রবণতা', help: 'সহায়তা', signIn: 'সাইন ইন', dashboard: 'অ্যাকাউন্ট', language: 'ভাষা',
    kicker: 'ভারতে উড়ানের আরও বুদ্ধিমান উপায়', headline1: 'যেখানে ইচ্ছা যান।', headline2: 'সঠিক ভাড়া বুঝুন।', heroText: 'এই ভাড়া কি সত্যিই ভালো? একই ধরনের যাত্রার সঙ্গে তুলনা করুন, সাশ্রয়ী তারিখ খুঁজুন এবং পছন্দের রুটে নজর রাখুন।', explore: 'রুট দেখুন', how: 'কীভাবে কাজ করে', start: 'এখান থেকে শুরু', where: 'কোথায় যাচ্ছেন?', choose: 'উপলব্ধ রুট বেছে নিন। মানচিত্র আপনার যাত্রা অনুযায়ী বদলাবে।', from: 'থেকে', to: 'পর্যন্ত', check: 'রুট দেখুন', quick: 'জনপ্রিয় রুট', simulated: 'ভাড়ার বিশ্লেষণ কৃত্রিম তথ্যের উপর ভিত্তি করে।',
    way: 'SKYMETRICS যেভাবে সাহায্য করে', story1: 'ভাড়া একটি সংখ্যা।', story2: 'সিদ্ধান্তের পেছনে গল্প আছে।', storyText: 'দামের বাইরেও ভাড়ার ধরন দেখুন। SkyMetrics আপনার পরের পদক্ষেপ বুঝতে সাহায্য করে।', context: 'ভাড়ার তুলনা', contextTitle: 'এই যাত্রার ভাড়া কি ভালো?', contextText: 'একই রুট ও কাছাকাছি বুকিং সময়ের ভাড়ার সঙ্গে তুলনা করুন।', contextAction: 'ভাড়া দেখুন', dates: 'তারিখ বাছুন', datesTitle: 'এক দিনে দাম বদলাতে পারে।', datesText: 'তারিখ ঠিক করার আগে আশেপাশের দিনগুলির ভাড়া দেখুন।', datesAction: 'তারিখ দেখুন', trips: 'আপনার যাত্রা', tripsTitle: 'জরুরি রুটে নজর রাখুন।', tripsText: 'যাত্রা সংরক্ষণ করুন, রুট অনুসরণ করুন এবং লক্ষ্য ভাড়া ঠিক করুন।', tripsAction: 'ড্যাশবোর্ড খুলুন', closingLabel: 'পরের যাত্রা শুরু হোক ভালো প্রশ্ন দিয়ে', closing: 'দামের পেছনের তথ্য জানতে চান?', getStarted: 'শুরু করুন', dataNote: 'SkyMetrics কৃত্রিম ভারতীয় ঘরোয়া ভাড়ার একটি গবেষণা প্রোটোটাইপ। এখানে লাইভ টিকিটের দাম বা সরকারি CPI নেই।',
  },
  mr: {
    flights: 'उड्डाणे', insights: 'मार्गाची माहिती', trends: 'भाड्याचा कल', help: 'मदत', signIn: 'साइन इन', dashboard: 'खाते', language: 'भाषा',
    kicker: 'भारतात उड्डाणाचा अधिक चांगला मार्ग', headline1: 'हवे तिथे जा.', headline2: 'योग्य भाडे समजून घ्या.', heroText: 'हे भाडे खरंच चांगले आहे का? समान प्रवासाशी तुलना करा, स्वस्त तारीख शोधा आणि आवडत्या मार्गावर लक्ष ठेवा.', explore: 'मार्ग पाहा', how: 'हे कसे चालते', start: 'येथून सुरुवात', where: 'कुठे उडणार आहात?', choose: 'उपलब्ध मार्ग निवडा. नकाशा तुमच्या प्रवासानुसार बदलेल.', from: 'कुठून', to: 'कुठे', check: 'मार्ग तपासा', quick: 'लोकप्रिय मार्ग', simulated: 'भाड्याचे विश्लेषण कृत्रिम डेटावर आधारित आहे.',
    way: 'SKYMETRICS कशी मदत करते', story1: 'भाडे हा एक आकडा आहे.', story2: 'निर्णयामागे एक गोष्ट आहे.', storyText: 'किमतीपलीकडचा कल पाहा. SkyMetrics पुढचे पाऊल ठरवायला मदत करते.', context: 'भाड्याची तुलना', contextTitle: 'या प्रवासासाठी भाडे योग्य आहे का?', contextText: 'त्याच मार्गावरील आणि समान बुकिंग वेळेतील भाड्याशी तुलना करा.', contextAction: 'भाडे तपासा', dates: 'तारीख निवडा', datesTitle: 'एका दिवसाने किंमत बदलू शकते.', datesText: 'तारीख ठरवण्याआधी आसपासच्या दिवसांचे भाडे पाहा.', datesAction: 'तारखा पाहा', trips: 'तुमचे प्रवास', tripsTitle: 'महत्त्वाच्या मार्गांवर लक्ष ठेवा.', tripsText: 'प्रवास जतन करा, मार्ग पाहा आणि अपेक्षित भाडे ठरवा.', tripsAction: 'डॅशबोर्ड उघडा', closingLabel: 'पुढील प्रवासाची सुरुवात चांगल्या प्रश्नाने', closing: 'किंमत अधिक नीट समजून घ्यायची आहे?', getStarted: 'सुरुवात करा', dataNote: 'SkyMetrics हा कृत्रिम भारतीय देशांतर्गत भाड्यांवर आधारित संशोधन नमुना आहे. येथे थेट तिकिट दर किंवा अधिकृत सरकारी CPI नाही.',
  },
  te: {
    flights: 'విమానాలు', insights: 'మార్గ సమాచారం', trends: 'ధరల ధోరణి', help: 'సహాయం', signIn: 'సైన్ ఇన్', dashboard: 'ఖాతా', language: 'భాష',
    kicker: 'భారతదేశంలో ప్రయాణానికి మెరుగైన మార్గం', headline1: 'మీకు నచ్చిన చోటికి వెళ్లండి.', headline2: 'సరైన ధరను తెలుసుకోండి.', heroText: 'ఈ ఛార్జీ నిజంగా మంచిదేనా? ఇలాంటి ప్రయాణాలతో పోల్చండి, తక్కువ ధర ఉన్న తేదీని కనుగొనండి, మీకు ఇష్టమైన మార్గాన్ని గమనించండి.', explore: 'మార్గాన్ని చూడండి', how: 'ఇది ఎలా పనిచేస్తుంది', start: 'ఇక్కడ ప్రారంభించండి', where: 'ఎక్కడికి వెళ్తున్నారు?', choose: 'అందుబాటులో ఉన్న మార్గాన్ని ఎంచుకోండి. మ్యాప్ మీ ప్రయాణానికి అనుగుణంగా మారుతుంది.', from: 'నుంచి', to: 'వరకు', check: 'మార్గాన్ని చూడండి', quick: 'ప్రముఖ మార్గాలు', simulated: 'ధరల విశ్లేషణ అనుకరణ డేటాపై ఆధారపడింది.',
    way: 'SKYMETRICS మీకు ఎలా తోడ్పడుతుంది', story1: 'ఛార్జీ ఒక సంఖ్య మాత్రమే.', story2: 'నిర్ణయానికి ఒక నేపథ్యం ఉంది.', storyText: 'ధర వెనుక ఉన్న ధోరణిని చూడండి. తదుపరి నిర్ణయం తీసుకోవడానికి SkyMetrics సహాయపడుతుంది.', context: 'ధర పోలిక', contextTitle: 'ఈ ప్రయాణానికి ధర బాగుందా?', contextText: 'అదే మార్గం మరియు సమానమైన బుకింగ్ సమయంలో ఉన్న ధరలతో పోల్చండి.', contextAction: 'ధరను చూడండి', dates: 'తేదీ ఎంపిక', datesTitle: 'ఒక్క రోజుతో ధర మారవచ్చు.', datesText: 'తేదీ నిర్ణయించే ముందు దగ్గరలోని రోజుల ధరలను పోల్చండి.', datesAction: 'తేదీలను చూడండి', trips: 'మీ ప్రయాణాలు', tripsTitle: 'ముఖ్యమైన మార్గాలను గమనించండి.', tripsText: 'ప్రయాణాలను సేవ్ చేయండి, మార్గాలను గమనించండి, లక్ష్య ధరను పెట్టండి.', tripsAction: 'డాష్‌బోర్డ్ తెరవండి', closingLabel: 'మీ తదుపరి ప్రయాణం మంచి ప్రశ్నతో మొదలవుతుంది', closing: 'ధర గురించి మరింత తెలుసుకోవాలా?', getStarted: 'ప్రారంభించండి', dataNote: 'SkyMetrics అనుకరణ భారతీయ దేశీయ విమాన ఛార్జీల పరిశోధన నమూనా. ఇది ప్రత్యక్ష టికెట్ ధరలు లేదా అధికారిక ప్రభుత్వ CPI చూపదు.',
  },
  ta: {
    flights: 'விமானங்கள்', insights: 'வழித்தடத் தகவல்', trends: 'கட்டணப் போக்கு', help: 'உதவி', signIn: 'உள்நுழைக', dashboard: 'கணக்கு', language: 'மொழி',
    kicker: 'இந்தியாவில் சிறந்த விமானப் பயணம்', headline1: 'விரும்பிய இடத்துக்குச் செல்லுங்கள்.', headline2: 'சரியான கட்டணத்தை அறியுங்கள்.', heroText: 'இந்தக் கட்டணம் உண்மையில் நல்லதா? இதே போன்ற பயணங்களுடன் ஒப்பிட்டு, குறைந்த கட்டணத் தேதியைத் தேர்ந்தெடுத்து, விருப்பமான வழித்தடத்தைக் கவனியுங்கள்.', explore: 'வழித்தடம் பார்க்க', how: 'எப்படிச் செயல்படுகிறது', start: 'இங்கே தொடங்குங்கள்', where: 'எங்கே பறக்கிறீர்கள்?', choose: 'கிடைக்கும் வழித்தடத்தைத் தேர்ந்தெடுக்கவும். வரைபடம் உங்கள் பயணத்துடன் மாறும்.', from: 'புறப்படும் இடம்', to: 'செல்லும் இடம்', check: 'வழித்தடம் பார்க்க', quick: 'பிரபல வழித்தடங்கள்', simulated: 'கட்டணப் பகுப்பாய்வு செயற்கைத் தரவை அடிப்படையாகக் கொண்டது.',
    way: 'SKYMETRICS உதவும் விதம்', story1: 'கட்டணம் ஒரு எண்.', story2: 'முடிவுக்குப் பின்னால் ஒரு கதை.', storyText: 'விலைக்கு அப்பால் அதன் போக்கையும் பாருங்கள். அடுத்த முடிவை எடுக்க SkyMetrics உதவுகிறது.', context: 'கட்டண ஒப்பீடு', contextTitle: 'இந்தப் பயணத்துக்கு கட்டணம் நல்லதா?', contextText: 'அதே வழித்தடம் மற்றும் ஒத்த முன்பதிவு நேரத்தின் கட்டணங்களுடன் ஒப்பிடுங்கள்.', contextAction: 'கட்டணம் பார்க்க', dates: 'தேதி தேர்வு', datesTitle: 'ஒரு நாளில் விலை மாறலாம்.', datesText: 'தேதியை முடிவு செய்வதற்கு முன் அருகிலுள்ள நாட்களை ஒப்பிடுங்கள்.', datesAction: 'தேதிகளைப் பார்க்க', trips: 'உங்கள் பயணங்கள்', tripsTitle: 'முக்கிய வழித்தடங்களைக் கவனியுங்கள்.', tripsText: 'பயணங்களைச் சேமித்து, வழித்தடங்களைப் பின்தொடர்ந்து, இலக்கு விலையை அமைக்கவும்.', tripsAction: 'டாஷ்போர்டைத் திறக்க', closingLabel: 'அடுத்த பயணம் நல்ல கேள்வியுடன் தொடங்குகிறது', closing: 'விலையை மேலும் புரிந்துகொள்ள விரும்புகிறீர்களா?', getStarted: 'தொடங்குங்கள்', dataNote: 'SkyMetrics என்பது செயற்கை இந்திய உள்நாட்டு விமானக் கட்டணங்களைப் பயன்படுத்தும் ஆய்வு மாதிரி. நேரடி டிக்கெட் விலைகள் அல்லது அதிகாரப்பூர்வ அரசு CPI இதில் இல்லை.',
  },
  gu: {
    flights: 'ફ્લાઇટ્સ', insights: 'માર્ગની માહિતી', trends: 'ભાડાનો વલણ', help: 'મદદ', signIn: 'સાઇન ઇન', dashboard: 'ખાતું', language: 'ભાષા',
    kicker: 'ભારતમાં ઉડવાની વધુ સારી રીત', headline1: 'જ્યાં ઇચ્છો ત્યાં જાઓ.', headline2: 'યોગ્ય ભાડું સમજો.', heroText: 'આ ભાડું ખરેખર સારું છે? સમાન મુસાફરી સાથે સરખાવો, સસ્તી તારીખ શોધો અને મનપસંદ માર્ગ પર નજર રાખો.', explore: 'માર્ગ જુઓ', how: 'આ કેવી રીતે કામ કરે છે', start: 'અહીંથી શરૂ કરો', where: 'તમે ક્યાં જઈ રહ્યા છો?', choose: 'ઉપલબ્ધ માર્ગ પસંદ કરો. નકશો તમારી મુસાફરી મુજબ બદલાશે.', from: 'ક્યાંથી', to: 'ક્યાં સુધી', check: 'માર્ગ તપાસો', quick: 'લોકપ્રિય માર્ગો', simulated: 'ભાડાનું વિશ્લેષણ કૃત્રિમ ડેટા પર આધારિત છે.',
    way: 'SKYMETRICS કેવી રીતે મદદ કરે છે', story1: 'ભાડું એક આંકડો છે.', story2: 'નિર્ણય પાછળ એક વાત છે.', storyText: 'માત્ર કિંમત નહીં, તેનો વલણ પણ જુઓ. SkyMetrics આગળનું પગલું સમજવામાં મદદ કરે છે.', context: 'ભાડાની સરખામણી', contextTitle: 'આ મુસાફરી માટે ભાડું સારું છે?', contextText: 'એ જ માર્ગ અને સમાન બુકિંગ સમયના ભાડા સાથે સરખાવો.', contextAction: 'ભાડું તપાસો', dates: 'તારીખ પસંદ કરો', datesTitle: 'એક દિવસથી કિંમત બદલાઈ શકે.', datesText: 'તારીખ નક્કી કરતા પહેલાં નજીકના દિવસોના ભાડા જુઓ.', datesAction: 'તારીખો જુઓ', trips: 'તમારી મુસાફરી', tripsTitle: 'મહત્વના માર્ગો પર નજર રાખો.', tripsText: 'મુસાફરી સાચવો, માર્ગ જુઓ અને લક્ષ્ય ભાડું નક્કી કરો.', tripsAction: 'ડેશબોર્ડ ખોલો', closingLabel: 'આગલી મુસાફરી સારા પ્રશ્નથી શરૂ થાય છે', closing: 'કિંમતને વધુ સારી રીતે સમજવા તૈયાર છો?', getStarted: 'શરૂ કરો', dataNote: 'SkyMetrics કૃત્રિમ ભારતીય ઘરેલુ ભાડા પર આધારિત સંશોધન નમૂનો છે. અહીં લાઇવ ટિકિટના ભાવ અથવા સત્તાવાર સરકારી CPI નથી.',
  },
  bho: {
    flights: 'उड़ान', insights: 'रूट के जानकारी', trends: 'किराया के रुझान', help: 'मदद', signIn: 'लॉग इन', dashboard: 'खाता', language: 'भाषा',
    kicker: 'भारत में उड़ान खातिर बेहतर तरीका', headline1: 'जहवाँ मन करे, जाईं।', headline2: 'किराया ठीक से बुझीं।', heroText: 'ई किराया सच में बढ़िया बा का? मिलत-जुलत सफर से तुलना करीं, सस्ता तारीख खोजीं आ अपना पसंद के रूट पर नजर रखीं।', explore: 'रूट देखीं', how: 'ई कइसे काम करेला', start: 'इहाँ से शुरू करीं', where: 'रउआ कहाँ उड़त बानी?', choose: 'उपलब्ध रूट चुनीं। नक्शा रउआ सफर के हिसाब से बदली।', from: 'कहाँ से', to: 'कहाँ तक', check: 'रूट जाँचीं', quick: 'लोकप्रिय रूट', simulated: 'किराया के हिसाब बनावल डेटा पर आधारित बा।',
    way: 'SKYMETRICS कइसे मदद करेला', story1: 'किराया एगो संख्या ह।', story2: 'फैसला के पीछे कहानी बा।', storyText: 'खाली दाम मत देखीं, ओकर रुझान भी बुझीं। SkyMetrics अगिला कदम चुने में मदद करेला।', context: 'किराया के तुलना', contextTitle: 'ई सफर खातिर किराया ठीक बा?', contextText: 'एके रूट आ मिलत-जुलत बुकिंग समय वाला किराया से तुलना करीं।', contextAction: 'किराया जाँचीं', dates: 'तारीख चुनीं', datesTitle: 'एक दिन से दाम बदल सकेला।', datesText: 'तारीख तय करे से पहिले आसपास के दिन के किराया देखीं।', datesAction: 'तारीख देखीं', trips: 'रउआ सफर', tripsTitle: 'जरूरी रूट पर नजर रखीं।', tripsText: 'सफर सेव करीं, रूट देखीं आ अपना मन मुताबिक किराया तय करीं।', tripsAction: 'डैशबोर्ड खोलीं', closingLabel: 'अगिला सफर बढ़िया सवाल से शुरू होला', closing: 'दाम के पीछे के बात बुझल चाहत बानी?', getStarted: 'शुरू करीं', dataNote: 'SkyMetrics भारत के घरेलू किराया के बनावल डेटा पर आधारित शोध नमूना ह। इहाँ लाइव टिकट के दाम भा सरकारी CPI नइखे।',
  },
}

const LocaleContext = createContext(null)

export function LocaleProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try { const saved = localStorage.getItem('skymetrics-language'); return languages.some(item => item.code === saved) ? saved : 'en' } catch { return 'en' }
  })
  useEffect(() => {
    document.documentElement.lang = language
    try { localStorage.setItem('skymetrics-language', language) } catch { /* private browsing */ }
  }, [language])
  const value = useMemo(() => ({ language, setLanguage, t: key => messages[language]?.[key] || messages.en[key] || key }), [language])
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>
}

export function useLocale() { return useContext(LocaleContext) }
